xiaotao/Areas/Dn/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using xiaotao.Models;

namespace xiaotao.Areas.Dn.Controllers
{
   [Filters.StuLoginAuthorize]
   public class ClaimController : Controller
   {
      private WebContext db = new WebContext();

      public ActionResult Index(int? states, int pageIndex = 1, int pageSize = 8)
      {
         var sid = int.Parse(Session["Sid"].ToString());
         var orders = db.dn_claim.Where(o => o.student == sid).ToList();

         ViewBag.state1 = orders.Where(e => e.states == 1).Count();
         ViewBag.state2 = orders.Where(e => e.states == 2).Count();

         if (states != null)
         {
            orders = orders.Where(e => e.states == states).ToList();
         }

         var Count = orders.Count();

         var pageCount = (Count % pageSize == 0) ? (Count / pageSize) : (Count / pageSize + 1);

         var queryString = "";
         if (states != null)
         {
            queryString = "states=" + states + "&";
         }

         ViewData["pager"] = Filters.Tools.PagerDesign(pageIndex, pageCount, "/dn/claim/index?" + queryString + "pageIndex=");

         return View(orders.Skip(pageSize * (pageIndex - 1)).Take(pageSize));
      }

      public ActionResult Details(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dn_claim dn_claim = db.dn_claim.Find(id);
         if (dn_claim == null)
         {
            return HttpNotFound();
         }
         return View(dn_claim);
      }

      public ActionResult Checkout(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         
         int sid = int.Parse(Session["Sid"].ToString());
         var goods = db.dn_goods.Find(id);

         if (goods == null)
         {
            return HttpNotFound();
         }
         ViewData["Address"] = db.xt_student_address.Where(e => e.student == sid).ToList();

         return View(goods);
      }

      public ActionResult Create()
      {
         ViewBag.goods = new SelectList(db.dn_goods, "id", "name");
         ViewBag.student = new SelectList(db.xt_student, "id", "email");
         return View();
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create(int gid)
      {
         var goods = db.dn_goods.Find(gid);
         if(goods == null)
         {
            return HttpNotFound();
         }
         var claim = new dn_claim();
         claim.states = 1;
         claim.create_at = DateTime.Now;
         claim.goods = gid;
         claim.student = int.Parse(Session["Sid"].ToString());

         // 更新物品上架状态
         db.Entry(goods).State = EntityState.Unchanged;
         db.Entry(goods).Property(e => e.is_onsale).IsModified = true;
         goods.is_onsale = false;

         db.dn_claim.Add(claim);
         db.SaveChanges();
         
         return RedirectToAction("Index");
      }

      public ActionResult Edit(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dn_claim dn_claim = db.dn_claim.Find(id);
         if (dn_claim == null)
         {
            return HttpNotFound();
         }
         ViewBag.goods = new SelectList(db.dn_goods, "id", "name", dn_claim.goods);
         ViewBag.student = new SelectList(db.xt_student, "id", "email", dn_claim.student);
         return View(dn_claim);
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "id,states,create_at,goods,student")] dn_claim dn_claim)
      {
         if (ModelState.IsValid)
         {
            db.Entry(dn_claim).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         ViewBag.goods = new SelectList(db.dn_goods, "id", "name", dn_claim.goods);
         ViewBag.student = new SelectList(db.xt_student, "id", "email", dn_claim.student);
         return View(dn_claim);
      }

      public ActionResult Delete(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dn_claim dn_claim = db.dn_claim.Find(id);
         if (dn_claim == null)
         {
            return HttpNotFound();
         }
         return View(dn_claim);
      }

      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         dn_claim dn_claim = db.dn_claim.Find(id);
         db.dn_claim.Remove(dn_claim);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

xiaotao/Areas/Dn/Controllers/GoodsListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using xiaotao.Models;

namespace xiaotao.Areas.Dn.Controllers
{
   public class GoodsListController : Controller
   {
      private WebContext db = new WebContext();
      public ActionResult Index(int pageIndex = 1, int pageSize = 8)
      {
         var goods = db.dn_goods.Where(e => e.is_onsale == true && e.is_delete == false).Include(e => e.dn_category).Include(e => e.xt_student);

         var Count = goods.Count();

         var pageCount = (Count % pageSize == 0) ? (Count / pageSize) : (Count / pageSize + 1);

         ViewData["pager"] = Filters.Tools.PagerDesign(pageIndex, pageCount, "/dn/goodslist/index?pageIndex=");

         return View(goods.ToList().Skip(pageSize * (pageIndex - 1)).Take(pageSize));
      }
   }
}

xiaotao/Areas/Dn/Views/Claim/Checkout.cshtml
@model xiaotao.Models.dn_goods

@{
   ViewBag.Title = "Details";
}

@section Styles {
   <style>
      .detail {
         margin-top: 50px;
      }

      .rank-box {
         clear: both;
      }

         .rank-box .text {
            width: 90px;
            font-size: 12px;
            height: 22px;
            line-height: 22px;
            color: #999;
            float: left;
         }

      .rank-bar {
         margin-top: 6px;
         background: #dedede;
         float: left;
         width: 100px;
         height: 10px;
      }

         .rank-bar .wrap {
            background: red;
            height: 10px;
         }

      .form-box {
         margin: 10px 0;
         padding: 10px;
         background: #eee;
         position: relative;
      }

      .cnt-user {
         position: absolute;
         width: 60px;
         height: 60px;
      }

      .cnt-textarea {
         height: 60px;
         margin-left: 70px;
      }

         .cnt-textarea textarea {
            max-width: 100%;
            height: 60px;
         }

      .form-bottom {
         margin-top: 10px;
      }
   </style>
}

<h3>认领详情</h3>

<div>
   <hr />
   <dl class="dl-horizontal">
      <dt>名称</dt>
      <dd>
         @Html.DisplayFor(model => model.name)
      </dd>

      <dt>图片</dt>
      <dd>
         @Html.DisplayFor(model => model.ori_img)
      </dd>

      <dt>分类</dt>
      <dd>
         @Html.DisplayFor(model => model.dn_category.name)
      </dd>

      <dt>是否匿名</dt>
      <dd>
         @Html.DisplayFor(model => model.is_anonymous)
      </dd>

      <dt>认领方式</dt>
      <dd>
         @Html.Raw((Model.claim_type==1)?"捐赠中心":"上门认领")
      </dd>

      @if (Model.claim_type == 2)
      {
         <dt>认领地址</dt>
         <dd>
            @Html.DisplayFor(model => model.claim_addr)
         </dd>
      }
   </dl>

   @using (Html.BeginForm("create", "claim", FormMethod.Post))
   {
      @Html.AntiForgeryToken()
      <input type="hidden" name="gid" value="@Model.id" />
      <dl class="dl-horizontal">
         <dt></dt>
         <dd style="padding-top:10px;">
            @if (Session["Sid"] != null && (Model.donor == int.Parse(Session["Sid"].ToString())))
            {
               <a class="btn btn-danger" href="/dn/goods/edit/@Model.id">编辑信息</a>
            }
            else
            {
               <button class="btn btn-danger" type="submit">立即认领</button>
            }
         </dd>
      </dl>
   }
</div>

@section Scripts {
   <script src="~/Scripts/angular.min.js"></script>
   
}

xiaotao/Areas/Dn/Views/Claim/Create.cshtml
@model xiaotao.Models.dn_claim

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>dn_claim</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.states, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.states, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.states, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.create_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.create_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.create_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.goods, "goods", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("goods", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.goods, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.student, "student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("student", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.student, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

xiaotao/Areas/Dn/Views/Claim/Delete.cshtml
@model xiaotao.Models.dn_claim

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>dn_claim</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dn_goods.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dn_goods.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.xt_student.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.xt_student.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.states)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.states)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_at)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

xiaotao/Areas/Dn/Views/Claim/Details.cshtml
@model xiaotao.Models.dn_claim

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>dn_claim</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.dn_goods.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dn_goods.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.xt_student.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.xt_student.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.states)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.states)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_at)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

xiaotao/Areas/Dn/Views/Claim/Edit.cshtml
@model xiaotao.Models.dn_claim

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>dn_claim</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.states, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.states, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.states, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.create_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.create_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.create_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.goods, "goods", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("goods", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.goods, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.student, "student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("student", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.student, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

xiaotao/Areas/Dn/Views/Claim/Index - 复制.cshtml
@model IEnumerable<xiaotao.Models.dn_claim>

@{
   ViewBag.Title = "Index";
}

<h2>Index</h2>

<style>
   .sort {
      margin-bottom: 20px;
      border: solid 1px #eee;
      background: #f5f5f5;
   }

   .sort a {
      display: inline-block;
      padding: 10px 15px;
      color: #666;
   }

   .sort a.active {
      border-left: solid 1px #eee;
      border-right: solid 1px #eee;
      background: #fff;
      color: #f40;
   }

   .sort a:first-child {
      border-left: none;
   }
   .lists .row {
      padding-top: 8px;
      padding-bottom: 8px;
      line-height: 1.42857143;
      vertical-align: top;
      border-top: 1px solid #ddd;
   }

   .thead {
      font-weight: bold;
      border-top: none;
      border-bottom: solid 1px #ddd;
   }

   .g-wrap {
      position: relative;
   }

   .g-img {
      position: absolute;
   }

   .g-info {
      margin-left: 50px;
      min-height: 40px;
   }
</style>

<p>
   @Html.ActionLink("去领取", "index","GoodsList")
</p>

<div class="row sort">
   <a href="/dn/claim/index">全部</a>
   <a data-states="1" href="/dn/claim/index?states=1">已申请 @Html.Raw(ViewBag.state1 == 0 ? "" : "<span class='badge'>" + @ViewBag.state1 + "</span>")</a>
   <a data-states="2" href="/dn/claim/index?states=2">已认领 @Html.Raw(ViewBag.state2 == 0 ? "" : "<span class='badge'>" + @ViewBag.state2 + "</span>")</a>
</div>

<div class="lists">
   <div class="row thead">
      <div class="col-xs-5">物品</div>
      <div class="col-xs-2">认领方式</div>
      <div class="col-xs-1">状态</div>
      <div class="col-xs-2">认领时间</div>
      <div class="col-xs-2">操作</div>
   </div>

   @foreach (var item in Model)
   {
      <div class="row">
         <div class="col-xs-5 g-wrap">
            <div class="g-img">
               <a href="#"><img width="40" src="~/Uploads/Products/@item.dn_goods.ori_img" alt="@item.dn_goods.name" /></a>
            </div>
            <div class="g-info">
               @Html.DisplayFor(modelItem => item.dn_goods.name)<br/>
               @(item.dn_goods.is_anonymous==true?"匿名捐赠":item.dn_goods.xt_student.sname)
            </div>
         </div>
         <div class="col-xs-2">
            <p>@(item.dn_goods.claim_type == 1 ? "捐赠中心" : "上门认领")</p>
            <p>@item.dn_goods.claim_addr</p>
         </div>
         <div class="col-xs-1">
            @switch (item.states)
            {
               case 0:
                  @Html.Raw("取消认领");
                  break;
               case 1:
                  @Html.Raw("申请认领");
                  break;
               case 2:
                  @Html.Raw("认领完成");
                  break;
            }
         </div>
         <div class="col-xs-2">
            @item.create_at.ToShortDateString()
         </div>
         <div class="col-xs-2">
            @Html.ActionLink("详情", "Details", new { id = item.id }) |
            @Html.ActionLink("删除", "Delete", new { id = item.id })
         </div>
      </div>
   }
</div>

@section Scripts{
   <script>
      var states = '@Request.QueryString["states"]'.toLowerCase();
      var sortLinks = $('.sort>a');
      if (states == '') {
         sortLinks.eq(0).addClass('active');
      } else {
         $.each(sortLinks, function (k, v) {
            if ($(v).attr('data-states') == states) {
               $(v).addClass('active');
            }
         })
      };
   </script>
}

xiaotao/Areas/Dn/Views/Claim/Index.cshtml
@model IEnumerable<xiaotao.Models.dn_claim>

@{
   ViewBag.Title = "Index";
}

<p>
   @Html.ActionLink("去领取", "index","GoodsList")
</p>

<div class="sort">
   <a href="/dn/claim/index">全部</a>
   <a data-states="1" href="/dn/claim/index?states=1">已申请 @Html.Raw(ViewBag.state1 == 0 ? "" : "<span class='badge'>" + @ViewBag.state1 + "</span>")</a>
   <a data-states="2" href="/dn/claim/index?states=2">已认领 @Html.Raw(ViewBag.state2 == 0 ? "" : "<span class='badge'>" + @ViewBag.state2 + "</span>")</a>
</div>

<div class="row-lists">
   <div class="row thead">
      <div class="col-xs-5">物品</div>
      <div class="col-xs-2">认领方式</div>
      <div class="col-xs-1">状态</div>
      <div class="col-xs-2">认领时间</div>
      <div class="col-xs-2">操作</div>
   </div>

   @foreach (var item in Model)
   {
      <div class="row oi-top">
         <div class="col-xs-12">
            <span>@item.create_at</span><span>订单号: @item.id</span>
         </div>
      </div>
      <div class="row oi-detail">
         <div class="col-xs-5 g-wrap">
            <div class="g-img">
               <a href="#"><img width="40" src="~/Uploads/Products/@item.dn_goods.ori_img" alt="@item.dn_goods.name" /></a>
            </div>
            <div class="g-info">
               <a href="/dn/goods/details/@item.goods">@item.dn_goods.name</a><br/>
               <span class="donor">@(item.dn_goods.is_anonymous == true ? "匿名捐赠" : item.dn_goods.xt_student.sname)</span>
            </div>
         </div>
         <div class="col-xs-2">
            <p>@(item.dn_goods.claim_type == 1 ? "捐赠中心" : "上门认领")</p>
            <p>@item.dn_goods.claim_addr</p>
         </div>
         <div class="col-xs-1">
            @switch (item.states)
            {
               case 0:
                  @Html.Raw("取消认领");
                  break;
               case 1:
                  @Html.Raw("申请认领");
                  break;
               case 2:
                  @Html.Raw("认领完成");
                  break;
            }
         </div>
         <div class="col-xs-2">
            @item.create_at.ToShortDateString()
         </div>
         <div class="col-xs-2">
            @Html.ActionLink("详情", "Details", new { id = item.id }) |
            @Html.ActionLink("删除", "Delete", new { id = item.id })
         </div>
      </div>
   }
</div>

<div class="row">
   <nav>
      <ul class="pagination">
         @Html.Raw(ViewData["pager"])
      </ul>
      @ViewBag.PageCount
   </nav>
</div>

@section Scripts{
   <script>
      var states = '@Request.QueryString["states"]'.toLowerCase();
      var sortLinks = $('.sort>a');
      if (states == '') {
         sortLinks.eq(0).addClass('active');
      } else {
         $.each(sortLinks, function (k, v) {
            if ($(v).attr('data-states') == states) {
               $(v).addClass('active');
            }
         })
      };
   </script>
}