xiaotao/Areas/Dn/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using xiaotao.Models;

namespace xiaotao.Areas.Dn.Controllers
{
   [Filters.StuLoginAuthorize]
   public class GoodsController : Controller
   {
      private WebContext db = new WebContext();

      public ActionResult Index()
      {
         var sid = int.Parse(Session["Sid"].ToString());
         var dn_goods = db.dn_goods.Where(e=>e.donor == sid).Include(d => d.dn_category).Include(d => d.xt_student);
         return View(dn_goods.ToList());
      }

      public ActionResult Claim()
      {
         var sid = int.Parse(Session["Sid"].ToString());
         var claims = db.dn_claim.Where(e => e.dn_goods.donor == sid);
         return View(claims.ToList());
      }

      [AllowAnonymous]
      public ActionResult Details(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dn_goods dn_goods = db.dn_goods.Find(id);
         if (dn_goods == null)
         {
            return HttpNotFound();
         }

         var claim = db.dn_claim.SingleOrDefault(e=>e.goods==id && e.states>=1);
         if (claim != null)
         {
            ViewBag.isClaim = true;
         }

         return View(dn_goods);
      }

      public ActionResult Create()
      {
         ViewBag.category = new SelectList(db.dn_category, "id", "name");
         return View();
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "id,name,ori_img,is_anonymous,claim_type,claim_addr,category")] dn_goods goods)
      {
         if (ModelState.IsValid)
         {
            if (Request.Files.Count > 0)
            {
               var file = Request.Files[0];
               if (file != null && file.ContentLength > 0)
               {
                  var fileName = Path.GetFileName(file.FileName);
                  var path = Path.Combine(Server.MapPath("~/Uploads/Products/"), fileName);
                  file.SaveAs(path);
                  goods.ori_img = fileName;
               }
            }

            goods.claim_addr = (goods.claim_type == 2) ? goods.claim_addr : null;

            goods.is_onsale = true;
            goods.is_delete = false;
            goods.create_at = DateTime.Now;
            goods.donor = int.Parse(Session["Sid"].ToString());

            db.dn_goods.Add(goods);
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         
         return View(goods);
      }

      public ActionResult Edit(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dn_goods dn_goods = db.dn_goods.Find(id);
         if (dn_goods == null)
         {
            return HttpNotFound();
         }
         ViewBag.category = new SelectList(db.dn_category, "id", "name", dn_goods.category);
         ViewBag.donor = new SelectList(db.xt_student, "id", "email", dn_goods.donor);
         return View(dn_goods);
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "id,name,ori_img,thumb_img,is_anonymous,is_onsale,is_delete,create_at,update_at,category,donor")] dn_goods dn_goods)
      {
         if (ModelState.IsValid)
         {
            db.Entry(dn_goods).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         ViewBag.category = new SelectList(db.dn_category, "id", "name", dn_goods.category);
         ViewBag.donor = new SelectList(db.xt_student, "id", "email", dn_goods.donor);
         return View(dn_goods);
      }

      public ActionResult Delete(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dn_goods dn_goods = db.dn_goods.Find(id);
         if (dn_goods == null)
         {
            return HttpNotFound();
         }
         return View(dn_goods);
      }

      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         dn_goods dn_goods = db.dn_goods.Find(id);
         db.dn_goods.Remove(dn_goods);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

xiaotao/Areas/Es/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using xiaotao.Models;

namespace xiaotao.Areas.Es.Controllers
{
   [Filters.StuLoginAuthorize]
   public class GoodsController : Controller
   {
      private WebContext db = new WebContext();

      public ActionResult Index(int pageIndex = 1, int pageSize = 8)
      {
         var stu = int.Parse(Session["Sid"].ToString());
         var goods = db.es_goods.Where(e => e.seller == stu).Include(e => e.es_category).Include(e => e.xt_student);

         var Count = goods.Count();

         var pageCount = (Count % pageSize == 0) ? (Count / pageSize) : (Count / pageSize + 1);

         ViewData["pager"] = Filters.Tools.PagerDesign(pageIndex, pageCount, "/es/goods/index?pageIndex=");

         return View(goods.ToList().Skip(pageSize * (pageIndex - 1)).Take(pageSize));
      }

      public ActionResult orders(int? states, int pageIndex = 1, int pageSize = 8)
      {
         var sid = int.Parse(Session["Sid"].ToString());
         var orders = db.es_order.Where(e => e.es_goods.seller == sid).OrderByDescending(e => e.create_at).ToList();

         ViewBag.state1 = orders.Where(e => e.states == 1).Count();
         ViewBag.state2 = orders.Where(e => e.states == 2).Count();
         ViewBag.state3 = orders.Where(e => e.states == 3).Count();

         if (states != null)
         {
            orders = orders.Where(e => e.states == states).ToList();
         }

         var Count = orders.Count();

         var pageCount = (Count % pageSize == 0) ? (Count / pageSize) : (Count / pageSize + 1);

         var queryString = "";
         if (states != null)
         {
            queryString = "states=" + states + "&";
         }

         ViewData["pager"] = Filters.Tools.PagerDesign(pageIndex, pageCount, "/es/goods/orders?" + queryString + "pageIndex=");

         return View(orders.Skip(pageSize * (pageIndex - 1)).Take(pageSize));
      }

      public ActionResult delivery(int? id)
      {
         var order = db.es_order.Find(id);
         return View(order);
      }

      [HttpPost]
      public ActionResult delivery(int id)
      {
         var order = db.es_order.Find(id);
         db.Entry(order).State = EntityState.Unchanged;
         db.Entry(order).Property(e => e.states).IsModified = true;
         order.states = 3;
         db.SaveChanges();
         return RedirectToAction("orders");
      }

      public ActionResult Trade(int? states, int pageIndex = 1, int pageSize = 8)
      {
         var sid = int.Parse(Session["Sid"].ToString());

         var orders = db.es_order.Where(e => e.es_goods.seller == sid).ToList();

         ViewBag.state1 = orders.Where(e => e.states == 1).Count();
         ViewBag.state2 = orders.Where(e => e.states == 2).Count();
         ViewBag.state3 = orders.Where(e => e.states == 3).Count();
         ViewBag.state4 = orders.Where(e => e.states == 4).Count();

         if (states != null)
         {
            orders = orders.Where(e=>e.states == states).ToList();
         }
         
         var Count = orders.Count();

         var pageCount = (Count % pageSize == 0) ? (Count / pageSize) : (Count / pageSize + 1);

         ViewData["pager"] = Filters.Tools.PagerDesign(pageIndex, pageCount, "/es/goods/Traded?pageIndex=");

         return View(orders.Skip(pageSize * (pageIndex - 1)).Take(pageSize));
      }

      [AllowAnonymous]
      public ActionResult Details(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         es_goods es_goods = db.es_goods.Find(id);
         if (es_goods == null)
         {
            return HttpNotFound();
         }

         var order = db.es_order.SingleOrDefault(e => e.goods == id && e.states >= 1);
         if (order != null)
         {
            ViewBag.isSold = true;
         }

         ViewBag.consultCount = db.es_consult.Where(e => e.goods == id).Count();
         return View(es_goods);
      }

      public ActionResult Create()
      {
         ViewBag.category = new SelectList(db.es_category, "id", "name");
         return View();
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "id,name,price,ori_img,is_new,is_onsale,category")] es_goods goods)
      {
         if (ModelState.IsValid)
         {
            if (Request.Files.Count > 0)
            {
               var file = Request.Files[0];
               if (file != null && file.ContentLength > 0)
               {
                  var fileName = Path.GetFileName(file.FileName);
                  var path = Path.Combine(Server.MapPath("~/Uploads/Products/"), fileName);
                  file.SaveAs(path);
                  goods.ori_img = fileName;
               }
            }

            goods.create_at = DateTime.Now;
            goods.seller = int.Parse(Session["Sid"].ToString());
            goods.is_delete = false;

            db.es_goods.Add(goods);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         ViewBag.category = new SelectList(db.es_category, "id", "name", goods.category);
         return View(goods);
      }

      public ActionResult Edit(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         es_goods es_goods = GetGoods(id);
         if (es_goods == null)
         {
            return HttpNotFound();
         }
         ViewBag.category = new SelectList(db.es_category, "id", "name", es_goods.category);
         return View(es_goods);
      }

      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "id,name,price,ori_img,is_new,is_onsale,category")] es_goods es_goods)
      {
         if (ModelState.IsValid)
         {
            db.Entry(es_goods).State = EntityState.Modified;

            if (es_goods.ori_img != null)
            {
               var file = Request.Files[0];
               if (file != null && file.ContentLength > 0)
               {
                  var fileName = Path.GetFileName(file.FileName);
                  var path = Path.Combine(Server.MapPath("~/Uploads/Products/"), fileName);
                  file.SaveAs(path);
                  es_goods.ori_img = fileName;
               }
            }
            else
            {
               db.Entry(es_goods).Property(e => e.ori_img).IsModified = false;
            }

            es_goods.update_at = DateTime.Now;

            db.Entry(es_goods).Property(e => e.create_at).IsModified = false;
            db.Entry(es_goods).Property(e => e.seller).IsModified = false;
            db.Entry(es_goods).Property(e => e.is_delete).IsModified = false;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         ViewBag.category = new SelectList(db.es_category, "id", "name", es_goods.category);
         return View(es_goods);
      }

      public ActionResult Delete(int? id)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         es_goods es_goods = db.es_goods.Find(id);
         if (es_goods == null)
         {
            return HttpNotFound();
         }
         return View(es_goods);
      }

      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         es_goods es_goods = db.es_goods.Find(id);
         db.es_goods.Remove(es_goods);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            db.Dispose();
         }
         base.Dispose(disposing);
      }

      private es_goods GetGoods(int? id)
      {
         int sid = int.Parse(Session["Sid"].ToString());
         return db.es_goods.Where(e => e.seller == sid).FirstOrDefault();
      }

      [AllowAnonymous]
      [HttpPost]
      public JsonResult GetConsult(int? id)
      {         
         var consults = db.es_consult.Where(e=>e.goods == id).ToList();
         var json = (from c in consults.Where(e=>e.ori_id==null)
                     select new
                     {
                        id = c.id,
                        writer = c.writer,
                        writerName = c.xt_student1.sname,
                        writeAvatar = c.xt_student1.avatar,
                        content = c.content,
                        ori_writer = c.ori_writer,
                        create_at = c.create_at.ToString(),
                        sub = (from s in consults.Where(e=>e.ori_id == c.id) select new {
                           id = s.id,
                           writer = s.writer,
                           writerName = s.xt_student1.sname,
                           writeAvatar = s.xt_student1.avatar,
                           content = s.content,
                           ori_writer = s.xt_student2.sno,
                           create_at = s.create_at.ToString(),
                        }).ToArray()
                     }).ToArray();
         return Json(json);
      }

      [AllowAnonymous]
      [HttpPost]
      public ActionResult SubmitConsult(string content,int gid,int? oid)
      {
         if (Session["Sid"] == null)
         {
            return Json(false);
         }

         es_consult consult = new es_consult();
         if(oid != null)
         {
            // 若是回复内容，则添加 顶级咨询条目和当前咨询条目的作者
            var cobj = db.es_consult.Find(oid);
            consult.ori_id = cobj.ori_id == null ? cobj.id : cobj.ori_id;
            consult.ori_writer = cobj.ori_writer == null ? cobj.writer : cobj.ori_writer;
         }

         consult.goods = gid;

xiaotao/Areas/Es/Views/Goods/Create.cshtml
@model xiaotao.Models.es_goods

@{
   ViewBag.Title = "Create";
}

<h3>发布物品</h3>

@using (Html.BeginForm(Html.BeginForm("create", "Goods", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
   @Html.AntiForgeryToken()

   <div class="form-horizontal">
      <hr />
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      <div class="form-group">
         @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         @Html.LabelFor(model => model.ori_img, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.EditorFor(model => model.ori_img, new { htmlAttributes = new { @type = "file", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ori_img, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
            <label class="checkbox-inline">
               @Html.EditorFor(model => model.is_new) 全新
               @Html.ValidationMessageFor(model => model.is_new, "", new { @class = "text-danger" })
            </label>
            <label class="checkbox-inline">
               @Html.EditorFor(model => model.is_onsale) 上架
               @Html.ValidationMessageFor(model => model.is_onsale, "", new { @class = "text-danger" })
            </label>
         </div>
      </div>

      <div class="form-group">
         @Html.LabelFor(model => model.category, "分类", htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.DropDownList("category", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="提交信息" class="btn btn-default" />
         </div>
      </div>
   </div>
}

<div>
   @Html.ActionLink("返回列表", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

xiaotao/Areas/Es/Views/Goods/Delete.cshtml
@model xiaotao.Models.es_goods

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>es_goods</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.es_category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.es_category.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.xt_student.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.xt_student.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ori_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ori_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.thumb_img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thumb_img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_new)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_new)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_onsale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_onsale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_delete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_delete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.create_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.create_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.update_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.update_at)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

xiaotao/Areas/Es/Views/Goods/Edit.cshtml
@model xiaotao.Models.es_goods

@{
   ViewBag.Title = "Edit";
   Layout = "~/Areas/Es/Views/Shared/_Layout_mini.cshtml";
}

<div class="clearfix" style="background:#eee; padding:0 10px;margin-bottom:20px;">
   <h4 class="pull-left">编辑物品信息(@Model.name)</h4>
   <div class="pull-right" style="padding-top: 10px;">
      @Html.ActionLink("添加发布", "Create")
   </div>
</div>


@using (Html.BeginForm(Html.BeginForm("Edit", "Goods", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
   @Html.AntiForgeryToken()
   <div class="form-horizontal">
      <hr />
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      @Html.HiddenFor(model => model.id)

      <div class="form-group">
         @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         @Html.LabelFor(model => model.ori_img, htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.EditorFor(model => model.ori_img, new { htmlAttributes = new { @type = "file", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ori_img, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
            <label class="checkbox-inline">
               @Html.EditorFor(model => model.is_new) 全新
               @Html.ValidationMessageFor(model => model.is_new, "", new { @class = "text-danger" })
            </label>
            <label class="checkbox-inline">
               @Html.EditorFor(model => model.is_onsale) 上架
               @Html.ValidationMessageFor(model => model.is_onsale, "", new { @class = "text-danger" })
            </label>
         </div>
      </div>

      <div class="form-group">
         @Html.LabelFor(model => model.category, "分类", htmlAttributes: new { @class = "control-label col-md-2" })
         <div class="col-md-10">
            @Html.DropDownList("category", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
         </div>
      </div>

      <div class="form-group">
         <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="保存信息" class="btn btn-default" />
         </div>
      </div>
   </div>
}

<div>
   @Html.ActionLink("返回列表", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

xiaotao/Areas/Es/Views/Goods/Index.cshtml
@model IEnumerable<xiaotao.Models.es_goods>

@{
   ViewBag.Title = "Index";
   Layout = "~/Areas/Es/Views/Shared/_Layout_mini.cshtml";
}

<style>
   #glist .media-left {
   }

      #glist .media-left a {
         width: 80px;
         display: block;
      }

      #glist .media-left img {
         width: 100%;
      }

   #glist .media-heading {
      font-size: 15px;
   }

   .single-row {
      font-size: 13px;
      color: #999;
   }

   .category {
      margin-right: 20px;
   }

   .price {
      margin-top: 8px;
      margin-bottom: 5px;
      color: #f40;
      font-weight: 700;
      font-family: Verdana,Tahoma,arial;
   }

   #glist .media-heading a {
      color: #666;
   }
</style>

<div class="clearfix" style="background:#eee; padding:0 10px;margin-bottom:20px;">
   <h4 class="pull-left">我的物品</h4>
   <div class="pull-right" style="padding-top: 10px;">
      @Html.ActionLink("添加发布", "Create")
   </div>
</div>

<table class="table table-hover" id="glist">
   <thead>
      <tr>
         <th class="col-md-6">商品</th>
         <th>全新</th>
         <th>状态</th>
         <th>操作</th>
      </tr>
   </thead>
   <tbody>
      @foreach (var item in Model)
      {
         <tr>
            <td>
               <div class="media">
                  <div class="media-left">
                     <a href="/es/goods/detail/@item.id">
                        <img src="~/Uploads/Products/@item.ori_img" alt="@item.name" />
                     </a>
                  </div>
                  <div class="media-body">
                     <h4 class="media-heading"><a href="/es/goods/detail/@item.id">@Html.DisplayFor(modelItem => item.name)</a></h4>
                     <div class="price">
                        <span class="glyphicon glyphicon-yen"></span>
                        <span>@Html.DisplayFor(modelItem => item.price)</span>
                     </div>
                     <div class="clearfix single-row">
                        <div class="category pull-left">
                           <span class="glyphicon glyphicon-tags"></span>
                           <span>@Html.DisplayFor(modelItem => item.es_category.name)</span>
                        </div>
                        <div class="time pull-left">
                           <span class="glyphicon glyphicon-time"></span>
                           <span>@string.Format("{0:d}", item.create_at)</span>
                        </div>
                     </div>
                  </div>
               </div>
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.is_new)
            </td>
            <td>
               @(item.is_onsale == true ? "正在出售" : "已售出")
            </td>
            <td>
               @if (item.is_onsale == true)
               {
                  @Html.ActionLink("修改", "Edit", new { id = item.id }) <span>|</span>
               }
               @Html.ActionLink("详情", "Details", new { id = item.id }) |
               @Html.ActionLink("删除", "Delete", new { id = item.id })
            </td>
         </tr>
      }
   </tbody>
</table>

<div class="row">
   <nav>
      <ul class="pagination">
         @Html.Raw(ViewData["pager"])
      </ul>
      @ViewBag.PageCount
   </nav>
</div>

xiaotao/Areas/Es/Views/Goods/delivery.cshtml
@model xiaotao.Models.es_order

@{
    ViewBag.Title = "delivery";
}

<div class="row panel panel-success">
   <div class="panel-heading">物品发货</div>
   <div class="panel-body">
      <dl class="dl-horizontal">
         <dt>订单号</dt>

         <dd>
            @Html.DisplayFor(model => model.id)
         </dd>
         <dt>
            @Html.DisplayNameFor(model => model.es_goods.name)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.es_goods.name)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.xt_student.email)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.xt_student.email)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.amount)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.amount)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.is_pay)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.is_pay)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.receiver)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.receiver)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.addr)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.addr)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.phone)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.phone)
         </dd>

         <dt>
            @Html.DisplayNameFor(model => model.create_at)
         </dt>

         <dd>
            @Html.DisplayFor(model => model.create_at)
         </dd>

      </dl>
   </div>
   <div class="panel-footer">
      @using (Html.BeginForm(Html.BeginForm()))
      {
         @Html.AntiForgeryToken()
         @Html.HiddenFor(model => model.id)
         <button type="submit" class="btn btn-danger">发货</button>
      }
   </div>
</div>